### ISSUE TITLE
Question on Differences Between the Samples...

### ISSUE THREAD

**Issue by madmacks59** [tgalarneau/bms#18]
So, I got the code working for the 4-socket version and was getting nice data on the battery and the cells displayed to the console. Based on that I decided to set up an MQTT broker and use the 4-mqtt version. I got thur that and started up the mqtt script, and it actually worked (broker and client on the same machine as the python code), the client terminal window received data...great news! But, I then noticed that the data the client was getting was very different that the data I'd seen for the 4-socket version script. I assumed these scripts were dumping the same data, just using different output methods. 

Is that the case? If it is then I've somehow messed something up in my tweaking of the python code. If the scripts do in fact dump different data, then I guess i'll need to do some code changes to get the data I'm looking for (like the data that came out of the socket script).

Also, for the command line options, I'm unclear about the -i option. I assumed it was something line "-i 10" meaning every 10 seconds, or minutes. But that is clearly not the case. Can you provide a bit more information on what the command options are and their specific meaning? Or point me to where that info exists if I've missed it?

This is an awesome project and will be VERY handy for me as I live off grid and have 5 separate solar systems spread over 40 acres, and it's a PITA to walk around with my iPhone/iPad getting readings when I need them., so nice job and thank you!

**Comment by tgalarneau** [comment]
The -i flag is seconds per data request. This is in addition to time required for script processing (~2 seconds). The -m is for the name you want to use for this data source. The -b is the mac address.

I'm not sure but besides the data timing differences of socket verses mqtt there is also the format. I believe one is a json (mqtt) format the other is cvs format (socket). Data may not be identical but close due to timing differences.

**Comment by madmacks59** [comment]
OK. For some reason I assumed the -i was in minutes. durp. I'll make some changes and rerun things. I guessing the different messages might be due to the fact II was running with 1 or 2 for the -i option and that was truncating the messages be delivered via MQTT vs dumped to the terminal. Thx!

**Comment by madmacks59** [comment]
After adjusting here's the output from the MQTT code...
Client (null) received PUBLISH (d0, q0, r0, m0, 'solar', ... (176 bytes))
{"meter": "bms", "c16": 0, "c15": 0, "c14": 0, "c13": 0, "c12": 0, "c11": 0, "c10": 0, "c09": 0, "c08": 0, "c07": 0, "c06": 0, "c05": 0, "c04": 0, "c03": 0, "c02": 0, "c01": 0}

And here's the output from the socket code...
meter,volts,amps,watts,remain,capacity,cycles
solar,13.35,0.00,0.00,274,280,0
meter,c01,c02,c03,c04,c05,c06,c07,c08
solar,0,0,0,0,0,0,0,0
meter,c09,c10,c11,c12,c13,c14,c15,c16
solar,0,0,0,0,0,0,0,0
meter,cell1,cell2,cell3,cell4
solar,3338,3340,3339,3340
meter,cellmin,cellmax,delta
solar,3338,3340,2
So there is a difference,, apparently, in the two programs. I'll check them out to see if I can find the difference...

**Comment by madmacks59** [comment]
Learning MQTT... Looks like i may not have subscribed to all the messages...not sure about gauge and topic...but I'll get there...

**Comment by tgalarneau** [comment]
Not sure what's going on with your socket data. 

But the mqtt data is correct but you have only received one data message. You are missing the other 4 messages.

**Comment by tgalarneau** [comment]
Actually cvs data looks correct.

**Comment by tgalarneau** [comment]
Best if just dump data to Telegraf and database for Grafana display.

**Comment by madmacks59** [comment]
trying to understand the following...
topic ="data/bms"
gauge ="data/bms/gauge"
 
in the code for the mqtt the first message is sent to "gauge" and the second is sent to "topic"...

like I said, learning mqtt...

**Comment by madmacks59** [comment]
in my application I'm going to push the data into a MySQL DB, which I use for other environmental data storage (i.e. well level, water tank level, etc). I have a presentation layer already built to display the status of a variety of other things. So for me it's "monitor device -> MQTT Broker -> MQTT client on DB server -> into DB", then a separate web server that reads and generates the presentation layer... So I'm going to skip the Telefraf and Grafana stuff. If course, as I get more familiar with the tools you implemented I may rebuild my system using them. But, I live way off grid and don't want to rely to much on external resources for the presentation layer...

**Comment by madmacks59** [comment]
Yep, looks like it was a publish topic issue. I the MQTT code you used Topic and Guage variables as the "topic" in the publish message. I was only subscribed to the value I'd used in the Topic variable... I'm getting it all now...

**Comment by tgalarneau** [comment]
MySQL will work but a time-series db is much easier and with Grafana very simple to build great graphical data and combining multiple devices and databases to see everything at a glance.

Happy experimenting.
